/**
 * CPU-mode validation of the Inflect-Micro-v2 graph executor against
 * reference outputs generated by onnxruntime (see refgen.py).
 * Run: bun run inflect-tts/tests/validate-cpu.ts
 */
import { readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { GraphExecutor } from '../executor.ts';
import type { CpuTensor } from '../tensor.ts';

const HERE = join(dirname(fileURLToPath(import.meta.url)), '..');
const DATA = join(HERE, 'testdata');

function loadNpy(path: string): { dims: number[]; data: Float32Array | BigInt64Array } {
  const buf = readFileSync(path);
  const bytes = new Uint8Array(buf);
  if (bytes[0] !== 0x93 || bytes[1] !== 0x4e) throw new Error('bad npy magic');
  const major = bytes[6];
  let headerLen: number, headerStart: number;
  const dv = new DataView(buf.buffer, buf.byteOffset);
  if (major === 1) { headerLen = dv.getUint16(8, true); headerStart = 10; }
  else { headerLen = dv.getUint32(8, true); headerStart = 12; }
  const header = new TextDecoder().decode(bytes.subarray(headerStart, headerStart + headerLen));
  const shape = (header.match(/shape['"]\s*:\s*\(([^)]*)\)/)?.[1] ?? '')
    .split(',').map((s) => s.trim()).filter(Boolean).map(Number);
  const descr = header.match(/descr['"]\s*:\s*'([^']*)'/)?.[1] ?? '<f4';
  const off = headerStart + headerLen;
  const n = shape.reduce((a, b) => a * b, 1);
  if (descr === '<i8' || descr.includes('i8')) {
    const out = new BigInt64Array(n);
    for (let j = 0; j < n; j++) {
      out[j] = dv.getBigInt64(off + j * 8, true);
    }
    return { dims: shape, data: out };
  }
  const f32 = new Float32Array(n);
  // copy to aligned buffer
  const tmp = new Uint8Array(n * 4);
  tmp.set(bytes.subarray(off, off + n * 4));
  f32.set(new Float32Array(tmp.buffer));
  return { dims: shape, data: f32 };
}

function maxAbsDiff(a: CpuTensor, ref: ReturnType<typeof loadNpy>): number {
  if (a.data.length !== ref.data.length) throw new Error(`size mismatch ${a.data.length} vs ${ref.data.length}`);
  let mx = 0;
  for (let j = 0; j < a.data.length; j++) {
    const d = Math.abs(Number(a.data[j]) - Number(ref.data[j]));
    if (d > mx) mx = d;
  }
  return mx;
}

async function main() {
  const tokensNpy = loadNpy(join(DATA, 'ref_tokens.npy'));
  const tokens = new BigInt64Array(tokensNpy.data.length);
  tokens.set(tokensNpy.data as BigInt64Array);

  const lsNpy = loadNpy(join(DATA, 'ref_length_scale.npy'));
  const lengthScale = (lsNpy.data as Float32Array)[0];

  console.log(`tokens T=${tokens.length}, length_scale=${lengthScale}`);

  // ── duration graph ──
  const durBuf = readFileSync(join(DATA, 'duration.onnx'));
  const durEx = new GraphExecutor(durBuf.buffer.slice(durBuf.byteOffset, durBuf.byteOffset + durBuf.byteLength));
  await durEx.init(null); // pure CPU

  const t0 = performance.now();
  const durOut = await durEx.run(
    new Map<string, CpuTensor>([
      ['tokens', { dims: [1, tokens.length], type: 'i64', data: tokens }],
      ['lengths', { dims: [1], type: 'i64', data: new BigInt64Array([BigInt(tokens.length)]) }],
      ['length_scale', { dims: [], type: 'f32', data: new Float32Array([lengthScale]) }],
    ]),
    ['m_p_exp', 'logs_p_exp', 'y_mask'],
  );
  console.log(`duration graph: ${(performance.now() - t0).toFixed(0)} ms`);

  for (const [name, file, tol] of [
    ['m_p_exp', 'ref_m_p_exp.npy', 2e-4],
    ['logs_p_exp', 'ref_logs_p_exp.npy', 2e-4],
    ['y_mask', 'ref_y_mask.npy', 1e-6],
  ] as const) {
    const got = durOut.get(name)!;
    const ref = loadNpy(join(DATA, file));
    if (got.dims.join() !== ref.dims.join()) throw new Error(`${name} dims ${got.dims} != ${ref.dims}`);
    const diff = maxAbsDiff(got, ref);
    const ok = diff <= tol;
    console.log(`${name}: dims=${got.dims} maxDiff=${diff.toExponential(3)} ${ok ? 'OK' : 'FAIL (tol ' + tol + ')'}`);
    if (!ok) process.exitCode = 1;
  }

  // ── decode graph ──
  const zpNpy = loadNpy(join(DATA, 'ref_zp_noise.npy'));
  const decBuf = readFileSync(join(DATA, 'decode.onnx'));
  const decEx = new GraphExecutor(decBuf.buffer.slice(decBuf.byteOffset, decBuf.byteOffset + decBuf.byteLength));
  await decEx.init(null);

  const t1 = performance.now();
  const wavOut = await decEx.run(
    new Map<string, CpuTensor>([
      ['m_p_exp', durOut.get('m_p_exp')!],
      ['logs_p_exp', durOut.get('logs_p_exp')!],
      ['y_mask', durOut.get('y_mask')!],
      ['zp_noise', { dims: zpNpy.dims, type: 'f32', data: zpNpy.data as Float32Array }],
      ['noise_scale', { dims: [], type: 'f32', data: new Float32Array([0.667]) }],
    ]),
    ['waveform'],
  );
  console.log(`decode graph: ${(performance.now() - t1).toFixed(0)} ms`);

  const wav = wavOut.get('waveform')!;
  const refWav = loadNpy(join(DATA, 'ref_waveform.npy'));
  const diff = maxAbsDiff(wav, refWav);
  console.log(`waveform: dims=${wav.dims} maxDiff=${diff.toExponential(3)} ${diff <= 5e-4 ? 'OK' : 'FAIL (tol 5e-4)'}`);
  if (diff > 5e-4) process.exitCode = 1;
}

await main();
